name: AWS DEPLOY TO STAGING

#turn off deploy to AWS
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    #For google auth

    steps:
      - uses: actions/checkout@v2
        # may need to change to version 3
        with:
          ref: main
      - uses: actions/setup-node@v3
        #May need to change to version 18
        with:
          node-version: 16

      - run: npm install
      - run: npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: "ec2-54-234-254-60.compute-1.amazonaws.com"
          REMOTE_USER: ubuntu
          TARGET: "/var/www/html/Travel-frontend"